#!/usr/bin/env bash
# Set Desktop Background
hsetroot -solid "#8FA1B3"

# Start compositor
picom --dbus -b

# Start Dunst Notification Daemon
dunst &

# Numlock state save
numlockx &

# Unclutter mouse cursor
unclutter &

# Add fonts to path and rehash
xset fp+ /usr/share/fonts/misc
xset fp+ /usr/share/fonts/local
xset fp rehash

# Set default cursor
xsetroot -cursor_name left_ptr

# Source Xresources
xrdb ~/.Xresources

# Load machine specific keyboard mappings
if [ -s ~/.Xmodmap ]; then
    xmodmap ~/.Xmodmap
fi

# Map CapsLock to Super
setxkbmap -option caps:super

# Start Simple X Hotkey Daemon
export SXHKD_SHELL='/usr/bin/sh'
sxhkd &

# Monitor Scripts
battmon &

# Gnome-Keyring
dbus-update-activation-environment --systemd DISPLAY
eval "$(/usr/bin/gnome-keyring-daemon --start --components=secrets)"

# Autorandr display management
if command -v autorandr; then
    autorandr -c
fi

# Start Polkit agent
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Start Window Manager
exec bspwm
