#!/bin/sh

source ~/.config/global.conf

clock() {
    date=$(date +"%a, %b %-d")
    time=$(date +"%I:%M %p")
    dunstify -r 90234 "Date" "$date $time" -i "/usr/share/icons/elementary/apps/symbolic/office-calendar-symbolic.svg"
}
clock
