#!/bin/sh

source ~/.config/global.conf

calendar() {
    dunstify -r 90235 "$(date +"%B %Y")" "$(cal | awk 'NF>2{print}')" -i "/usr/share/icons/elementary/apps/symbolic/office-calendar-symbolic.svg"
}
calendar
