#!/usr/bin/env fish

set BG "343D46FF"
set BGLITE "65737EFF"
set FG "C0C5CEFF"
set RED "BF616AFF"
set GRN "A3BE8CFF"

set disp (string replace ':' "_" $DISPLAY)

# Suspend notifications
dunstctl set-paused true

i3lock -n -e --clock \
             --force-clock \
             --time-pos="x+100:y+56" \
             --date-pos="tx+25:ty+25" \
             --ind-pos="x+210:y+55" \
             --time-str="%l:%M %p" \
             --date-str="%a, %b %d" \
             --radius=20 \
             --ring-width=2 \
             --verif-text="" \
             --wrong-text="" \
             --noinput-text="" \
             --line-uses-inside \
             --color=343D46 \
             --time-color=$FG \
             --date-color=$FG \
             --verif-color=FFFFFF00 \
             --wrong-color=FFFFFF00 \
             --separator-color=$FG \
             --ring-color=$FG \
             --keyhl-color=$BGLITE \
             --bshl-color=$RED \
             --inside-color=$BG \
             --insidever-color=$GRN \
             --insidewrong-color=$RED \
             --ringver-color=$GRN \
             --ringwrong-color=$RED

# Resume notifications
dunstctl set-paused false
