#!/usr/bin/env bash

# Two other files must be present for this script to work properly.
#
# /etc/modprobe.d/v4l2loopback.conf
# ===
# options v4l2loopback video_nr=11 card_label="ElGato FaceCam" exclusive_caps=1
#
# /etc/modules-load.d/v4l2loopback.conf
# ===
# v4l2loopback


# The following lines re-establish the USB connection to the camera
# since occassionally the camera needs to be reconnected for ffmpeg
set -euo pipefail
IFS=$'\n\t'

# Get these values from `lsusb`
VENDOR="0fd9" # Elgato Vendor
PRODUCT="0078" # Facecam ID
FACECAM_DEVICE_PATH="/dev/v4l/by-id/usb-Elgato_Elgato_Facecam_FW47K1A08546-video-index0"

for DIR in $(find /sys/bus/usb/devices/ -maxdepth 1 -type l); do
  if [[ -f $DIR/idVendor && -f $DIR/idProduct &&
        $(cat $DIR/idVendor) == $VENDOR && $(cat $DIR/idProduct) == $PRODUCT ]]; then
    echo 0 | sudo tee -a $DIR/authorized > /dev/null
    sleep 0.5
    echo 1 | sudo tee -a $DIR/authorized > /dev/null
  fi
done

sleep 1

v4l2-ctl -d "$FACECAM_DEVICE_PATH" --set-ctrl="brightness=130,contrast=3,saturation=33,sharpness=2,zoom_absolute=2"

# Create v4l2 loopback webcam for browsers and video conferencing apps to use
ffmpeg -hwaccel qsv -f v4l2 -input_format uyvy422 -framerate 60 -video_size 1920x1080 \
       -i "$FACECAM_DEVICE_PATH" \
       -pix_fmt yuyv422 -f v4l2 /dev/video11
