#!/bin/sh

source ~/.config/global.conf

network() {
    eth=''
    wifi=''
    interfaces=$(ip link show up | sed -n 's/^[0-9]: \(.*\):.*$/\1/p')
    for interface in $interfaces; do
        if [[ $interface == *"en"* ]] ; then
            if [[ $(cat /sys/class/net/$interface/operstate) = "up" ]] ; then
                if ip_addr=$(ip -4 addr show $interface| grep -oP '(?<=inet\s)\d+(\.\d+){3}') ; then
                    dunstify -r 82394 "$interface" "$ip_addr" -i "/usr/share/icons/elementary/status/symbolic/network-wired-symbolic.svg"
                else
                    dunstify -r 82394 "$interface" "Not connected" -i "/usr/share/icons/elementary/status/symbolic/network-wired-no-route-symbolic.svg"
                fi
            else
                dunstify -r 82394 "$interface" "Not connected" -i "/usr/share/icons/elementary/status/symbolic/network-wired-disconnected-symbolic.svg"
            fi
        elif [[ $interface == *"wl"* ]] ; then
            if [[ $(cat /sys/class/net/$interface/operstate) = "up" ]] ; then
                if ip_addr=$(ip -4 addr show $interface| grep -oP '(?<=inet\s)\d+(\.\d+){3}') ; then
                    dunstify -r 82395 "$(iwgetid -r)" "$ip_addr" -i "/usr/share/icons/elementary/status/symbolic/network-wireless-connected-symbolic.svg"
                else
                    dunstify -r 82395 "Wireless" "Not connected" -i "/usr/share/icons/elementary/status/symbolic/network-wireless-no-route-symbolic.svg"
                fi
            else
                dunstify -r 82395 "Wireless" "Not connected" -i "/usr/share/icons/elementary/status/symbolic/network-wireless-offline-symbolic.svg"
            fi
        fi
    done
}

network
